version: '3.8'

services:
  pulley-math-service:
    restart: on-failure
    build: .
    image: pulley-math:latest
    container_name: pulley-math
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://host.docker.internal/~/pulley;MODE=MYSQL
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin