---- 유닛 코드 테이블 (UnitCode)
--CREATE TABLE IF NOT EXISTS `unit_code` (
--    `sn` BIGINT AUTO_INCREMENT PRIMARY KEY,  -- 고유 ID
--    `code` VARCHAR(30) NOT NULL,             -- 유형 코드 (고유 값)
--    `name` VARCHAR(255) NOT NULL              -- 유형 이름
--);
--
---- 문제 테이블 (Problem)
--CREATE TABLE IF NOT EXISTS `problem` (
--    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,   -- 문제 ID
--    `unit_code_sn` BIGINT NOT NULL,            -- 유형 코드 외래 키 (UnitCode 테이블의 sn 참조)
--    `level` INT NOT NULL,                      -- 난이도
--    `type` VARCHAR(50) NOT NULL,              -- 문제 유형
--    `answer` INT NOT NULL,                     -- 정답
--    FOREIGN KEY (unit_code_sn) REFERENCES unit_code(sn) -- UnitCode 테이블의 sn 컬럼을 참조
--);